version: '3'

services:
  wound-care-guide:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./videos:/app/static/videos
    environment:
      - USE_S3=False
      # Uncomment and populate these for S3 integration
      # - S3_BUCKET_NAME=your-bucket-name
      # - AWS_ACCESS_KEY_ID=your-access-key
      # - AWS_SECRET_ACCESS_KEY=your-secret-key
      # - AWS_REGION=your-region
    restart: unless-stopped
